Module6 task1
htmlacademy-php/896717-doingsdone-12 pull request #10
Opened 2021-05-18 12:03 UTC by morozalexey

2021-05-20 06:46 UTC, ademaro commented on index.php
> +$cat_id = $_GET['cat_id'] ?? '';
Вместо пустой строки, думаю, логичнее false

2021-05-20 06:48 UTC, ademaro commented on index.php
> +        );
у тебя этот блок повторяется 3 раза, меняются только параметры в некоторых случаях, давай подумаем как вынести его (DRY)

2021-05-20 06:49 UTC, ademaro commented on templates/main.php
> +                    <a class="main-navigation__list-item-link" href="/?cat_id=<?= $category['id'] ; ?>"><?= $category['name'] ; ?></a>
давай ссылки не абсолютные, а относительные делать. И с чётким указанием контроллера: index.php?cat_id...

2021-05-20 06:49 UTC, ademaro commented on templates/main.php
> +                <li class="main-navigation__list-item <?= ($_GET['cat_id'] == $category['id']) ? 'main-navigation__list-item--active' : '' ; ?>
только строгое сравнение

2021-05-20 06:50 UTC, ademaro commented on templates/main.php
> +                    <?= (isset($_GET['cat_id'])) ? task_сount($all_tasks, $category['id']) : task_сount($tasks, $category['id']) ;?></span>
почитай разницу isset() и !empty()

2021-05-20 06:51 UTC, ademaro requested changes
Жду небольших поправок и двинем в следующее задание

2021-05-20 07:25 UTC, morozalexey commented on templates/main.php
> +                    <?= (isset($_GET['cat_id'])) ? task_сount($all_tasks, $category['id']) : task_сount($tasks, $category['id']) ;?></span>
ну на практике, насколько я понял, что применяя !empty() мы не получим ошибку, если переменная пустая, так что наверное лучше его юзать.

2021-05-21 13:29 UTC, ademaro commented on helpers.php
> +        if(empty(get_tasks_by_category($con, $cat_id))){
где-то ставишь пробелы после операторов — где-то нет, давай выберем стиль) По psr сразу хорошим тоном работать, тк есть формальный критерий по этому. Можешь поставить что-то подобное https://github.com/squizlabs/PHP_CodeSniffer или в виде плагина к редактору, что бы была подсветка таких мелочей

2021-05-21 13:33 UTC, ademaro commented on helpers.php
> +                'layout.php',
для страницы «не найдено» нам надо ещё менять заголовок HTTP (404) — давай так же потренируемся это реализовывать, было бы хорошо потом это внедрить и в авторизации/регистрации, например. Хотя бы почитай, сможем обсудить на голосовой консультации более подробно

2021-05-21 13:36 UTC, ademaro requested changes
Давай ещё финальные правки и перейдём дальше

2021-05-21 13:36 UTC, ademaro commented on helpers.php
> +                    'page_title' => "Дела в порядке"
двойные и одинарные кавычки — не очень круто смотрится, давай выберем что-то одно

2021-05-21 13:36 UTC, ademaro commented on helpers.php
> +function layout_content($con, $cat_id, $user_id, $show_complete_tasks){
вынесли в ф-цию, но не то, что нужно) вынес прям весь контроллер)) надо было только кусочек, там где повторяется только код. Если не очень понятно — давай вернём как было хотя бы, обсудим детальнее на консультации

2021-05-24 14:12 UTC, ademaro approved these changes

2021-05-24 14:12 UTC, ademaro commented on helpers.php
> +    ];
давай удалим и подумай когда созвониться всё-таки)

2021-05-24 14:12 UTC, merged

2021-05-24 14:23 UTC, morozalexey commented on helpers.php
> +    ];
Понял))