Module7 task2
htmlacademy-php/896717-doingsdone-12 pull request #14
Opened 2021-07-22 15:16 UTC by morozalexey

2021-07-23 23:22 UTC, ademaro commented on add.php
> +$user = $_SESSION['user'];
надо сделать проверку на наличие в сессии ключа

2021-07-23 23:24 UTC, ademaro commented on add.php
>  $show_complete_tasks = rand(0, 1);
эта строка лишняя тут

2021-07-23 23:27 UTC, ademaro commented on index.php
> +}
проверку на авторизацию можем сделать отдельной функцией, тк это нужно проверять в разны контроллерах

2021-07-23 23:27 UTC, ademaro commented on index.php
> +print_r($user);
не забудь удалить

2021-07-23 23:31 UTC, ademaro requested changes
жду небольших доработок + тож прикрепи к заданию

2021-07-27 06:32 UTC, morozalexey commented on add.php
>  $show_complete_tasks = rand(0, 1);
Почему? Функции из models.php используются в этом контроллере. Или может мне их сразу подключать в helpers.php, чтобы не было "DRY"?

2021-07-30 15:00 UTC, ademaro commented on add.php
>  if ($_SERVER['REQUEST_METHOD'] == 'POST') {
строгое сравнение

2021-07-30 15:03 UTC, ademaro commented on models.php
> +function create_user($con, $email)
наверное, не create_user, а get_user?

2021-07-30 15:04 UTC, ademaro commented on templates/guest.php
> +  <link rel="stylesheet" href="../css/normalize.css">
пути к статике — относительно корня делаем, а не папки шаблонов

2021-07-30 15:04 UTC, ademaro approved these changes
ок, двигаем дальше

2021-07-30 15:04 UTC, merged