мелкие правки после проверки наставника ветки 7.2
htmlacademy-php/896717-doingsdone-12 pull request #15
Opened 2021-08-13 06:49 UTC by morozalexey

2021-08-17 11:03 UTC, ademaro commented on helpers.php
> +    } else {
так else надо убрать, посмотри внимательнее критерий [Д7](https://up.htmlacademy.ru/php/12/criteries#d7)

2021-08-17 11:04 UTC, ademaro commented on add_category.php
> +$is_auth = $user['id'];
так если пользователь не авторизован, то  $user === false, соответственно $user['id'] будет ошибка

2021-08-17 11:05 UTC, ademaro commented on add_category.php
> +if ($_SERVER['REQUEST_METHOD'] == 'POST') {
всегда только строгое сравнение используем

2021-08-17 11:06 UTC, ademaro commented on index.php
> +    } elseif($search) {
пробел после elseif

2021-08-17 11:10 UTC, ademaro requested changes
давай   по мелочам подправим и двинем дальше

2021-08-17 11:10 UTC, merged

2021-08-18 05:58 UTC, morozalexey commented on add_category.php
> +$is_auth = $user['id'];
хм... так неавторизованный пользователь сюда попасть не может и добавлять категории тем более. Если он неавторизованный, то его перекидывает на гостевую страницу, где возможны только 2 действия  войти и зарегиться.

2021-08-18 13:42 UTC, ademaro commented on add_category.php
> +$is_auth = $user['id'];
так а где этот функционал с редиректом? Если я как неавторизованный пользователь открою `/add_category.php` — будет редирект? По коду не вижу...