циклом foreach добавил вывел задачи на странице проекта
htmlacademy-php/896717-doingsdone-12 pull request #3
Opened 2021-04-16 12:26 UTC by morozalexey

2021-04-16 14:24 UTC, ademaro commented on index.php
> +        'date' => '01.12.2019',
Рекомендую почитать стандарт хранения дат: https://ru.wikipedia.org/wiki/ISO_8601

2021-04-16 14:25 UTC, ademaro commented on index.php
> +$categories = ['Входящие', 'Учеба', 'Работа', 'Домашние дела', 'Авто'];
я бы сделал ассоциативный массив, нам для каждой категории понадобится ещё slug/alias, отпишу в шаблоне где именно...

2021-04-16 14:26 UTC, ademaro commented on index.php
> +        'category' => 'Работа',
Могли бы связать с предыдущим массивом. Пока не обязательно, но ради тренировки)

2021-04-16 14:28 UTC, ademaro commented on index.php
> +                    <?php foreach($tasks as $task => $item) : ?>
тут ты, похоже запутался) `<?php foreach($tasks as $task) : ?>` — так оставляем, дальше используем не $tasks[$task], а просто $task

2021-04-16 14:28 UTC, ademaro requested changes
Давай внесём мелкие правки и закрою

2021-04-16 18:25 UTC, morozalexey commented on index.php
> +        'category' => 'Работа',
правильно ли я понял? сделать например в массиве tasks в каждом ассоциативном массиве новые ключ-значение например 'category_name'=>'' ?

2021-04-17 10:32 UTC, ademaro commented on index.php
> +$categories = [
```php
$categories = [
  [
    'alias' => 'inbox',
    'name' => 'Входящие'
  ], [
    ...
  ]
];
```
или
```php
$categories = [
  'inbox' => 'Входящие',
  ...
];
```

2021-04-17 10:34 UTC, ademaro commented on index.php
> +        'category' => 'Работа',
А тут уже, например:
```php
$tasks = [    
    [
        'name' => 'Собеседование в IT компании',
        'date' => '2019-12-01',
        'category' => $categories['work'],
```

2021-04-17 10:35 UTC, ademaro commented on index.php
> +<pre><?php print_r($tasks);?></pre>
Для себя — проверяй, но не добавляй в коммит при отправке

2021-04-17 10:36 UTC, ademaro commented on index.php
> +                    <pre><?php //var_dump($tasks); ?></pre>
var_dump — тож удаляем

2021-04-17 10:43 UTC, ademaro requested changes
Жду поправкок

2021-04-17 14:02 UTC, ademaro commented on index.php
> +    'inbox' => 'Входящие',
👍🏼

2021-04-17 14:03 UTC, ademaro commented on index.php
> +                        <?php foreach($categories as $category => $item) :?>
почему тут item появился?))
`<?php foreach($categories as $category): ?>` нам достаточно)
https://www.php.net/manual/ru/control-structures.foreach.php — почитай подробнее, плиз

2021-04-17 14:03 UTC, ademaro approved these changes
Закрываю ПР, жду поправки в следующем задании отдельным коммитом сразу

2021-04-17 14:04 UTC, merged