исправил цикл в категориях
htmlacademy-php/896717-doingsdone-12 pull request #4
Opened 2021-04-19 06:09 UTC by morozalexey

2021-04-19 16:08 UTC, ademaro commented on index.php
> +function projectCount($arrTasks, $categoryName){
Почитай по phpDoc, это особый вид комментариев, давай сразу писать хорошо и для каждой ф-ции будем описывать в этом формате (есть в критериях). Примеры можешь подсмотреть в helpers.php

2021-04-19 16:10 UTC, ademaro commented on index.php
> +    foreach ($arrTasks as $item) {
arrTasks — просто tasks было бы достаточно, в именование переменных тип данных не стоит вписывать. `categoryName` меняем на `category_name`, в мире php принято snake_case вместо camelCase

2021-04-19 16:11 UTC, ademaro commented on index.php
> +    foreach ($arrTasks as $item) {
и переименуй переменную item

2021-04-19 16:12 UTC, ademaro commented on index.php
> +        if ($item['category'] !== $categoryName){
и почему от обратного?)) сравниваем, если соответствует — прибавляем)) Заодно тут пробел перед открывающей фигурной скобкой.

2021-04-19 16:13 UTC, ademaro commented on index.php
> +                            <a class="main-navigation__list-item-link" href="#"><?=$category;?></a>
👍🏼

2021-04-19 16:13 UTC, ademaro requested changes
Жду правок. В целом всё отлично пока что)

2021-04-19 19:51 UTC, ademaro commented on index.php
> +function projectCount($tasks, $category_name){
projectCount — так а чего не поправил название ф-ции?) project_count()

2021-04-19 19:54 UTC, ademaro commented on index.php
> +function projectCount($tasks, $category_name){
давай заодно пробежимся по стилизации, что бы потом не править: пробел перед открывающей фигурной скобкой

2021-04-19 19:56 UTC, ademaro commented on index.php
> + * Пройдя по массиву с задачами, функция сравнит значение выбранной категории ($category_name) со значением ключа ['category'] в каждой задаче. При совпадении она приплюсует единицу к $count.
описание особо не нужно, думаю. Ну или поставить до описания параметров (ну или после return)

2021-04-19 19:57 UTC, ademaro commented on index.php
> +
Разрыв строки не делают между phpDoc'ом и определением ф-ции...

2021-04-19 19:58 UTC, ademaro commented on index.php
> +                            <a class="main-navigation__list-item-link" href="#"><?=$category;?></a>
пробел после знака равно и после точки с запятой

2021-04-19 19:58 UTC, ademaro commented on index.php
>                          <?php endforeach;?>
пробел после точки с запятой

2021-04-19 19:59 UTC, ademaro commented on index.php
> +                        <?php foreach($categories as $category) :?>
пробел после двоеточия

2021-04-19 19:59 UTC, ademaro requested changes
Давай по стилистике ещё один коммит. За phpDoc — плюс, молодец!

2021-04-23 09:38 UTC, ademaro commented on index.php
> +                        <?php foreach($categories as $category) :?>
ты не все комменты от меня видишь?

2021-04-23 09:39 UTC, ademaro commented on index.php
> +                            <a class="main-navigation__list-item-link" href="#"><?=$category;?></a>
Вот, вроде ж описываю чётко на какой строке что поправить...

2021-04-23 09:39 UTC, ademaro approved these changes
Закрываю, но по единообразию — надо бы закрыть вопрос.

2021-04-23 09:39 UTC, merged

2021-04-23 10:25 UTC, morozalexey commented on index.php
> +                        <?php foreach($categories as $category) :?>
Походу проморгал, извиняюсь...